

CREATE DATABASE SISTEMA_ELECTORAL;
GO

USE SISTEMA_ELECTORAL;
GO



CREATE TABLE USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    CORREO VARCHAR(100) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    ROL VARCHAR(50) 
);


CREATE TABLE VOTANTES (
    ID_VOTANTES INT IDENTITY(1,1) PRIMARY KEY,
    DNI VARCHAR(20) NOT NULL,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    DISTRITO VARCHAR(100) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CANDIDATO_VOTADO VARCHAR(100),
    FECHA_VOTO DATETIME
);


CREATE TABLE VOTO_NULO (
    ID_VOTO_NULO INT IDENTITY(1,1) PRIMARY KEY,
    ID_VOTANTES INT NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_VOTANTES) REFERENCES VOTANTES(ID_VOTANTES)
);

CREATE TABLE CANDIDATO_PRESIDENCIAL (
    ID_CANDIDATO_PRESIDENCIAL INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    CANTIDAD_VOTOS INT DEFAULT 0
);


CREATE TABLE CANDIDATO_REGIONAL (
    ID_CANDIDATO_REGIONAL INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    CANTIDAD_VOTOS INT DEFAULT 0
);


CREATE TABLE CANDIDATO_DISTRITAL (
    ID_CANDIDATO_DISTRITAL INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    CANTIDAD_VOTOS INT DEFAULT 0
);


CREATE TABLE VOTO_PRESIDENCIAL (
    ID_VOTO_PRESIDENCIAL INT IDENTITY(1,1) PRIMARY KEY,
    ID_VOTANTES INT NOT NULL,
    ID_CANDIDATO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_VOTANTES) REFERENCES VOTANTES(ID_VOTANTES),
    FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO_PRESIDENCIAL(ID_CANDIDATO_PRESIDENCIAL)
);


CREATE TABLE VOTO_REGIONAL (
    ID_VOTO_REGIONAL INT IDENTITY(1,1) PRIMARY KEY,
    ID_VOTANTES INT NOT NULL,
    ID_CANDIDATO_REGIONAL INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_VOTANTES) REFERENCES VOTANTES(ID_VOTANTES),
    FOREIGN KEY (ID_CANDIDATO_REGIONAL) REFERENCES CANDIDATO_REGIONAL(ID_CANDIDATO_REGIONAL)
);


CREATE TABLE VOTO_DISTRITAL (
    ID_VOTO_DISTRITAL INT IDENTITY(1,1) PRIMARY KEY,
    ID_VOTANTES INT NOT NULL,
    ID_CANDIDATO_DISTRITAL INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DISTRITO VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_VOTANTES) REFERENCES VOTANTES(ID_VOTANTES),
    FOREIGN KEY (ID_CANDIDATO_DISTRITAL) REFERENCES CANDIDATO_DISTRITAL(ID_CANDIDATO_DISTRITAL)
);

CREATE TABLE RESULTADO_PRESIDENCIAL (
    ID_RESULTADO_PRESIDENCIAL INT IDENTITY(1,1) PRIMARY KEY,
    ID_CANDIDATO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TOTAL_VOTOS INT DEFAULT 0,
    FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO_PRESIDENCIAL(ID_CANDIDATO_PRESIDENCIAL)
);


CREATE TABLE RESULTADO_REGIONAL (
    ID_RESULTADO_REGIONAL INT IDENTITY(1,1) PRIMARY KEY,
    ID_CANDIDATO INT NOT NULL,
    NOMBRE_APELLIDO VARCHAR(200) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    TOTAL_VOTOS INT DEFAULT 0,
    FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO_REGIONAL(ID_CANDIDATO_REGIONAL)
);


CREATE TABLE RESULTADO_DISTRITAL (
    ID_RESULTADO_DISTRITAL INT IDENTITY(1,1) PRIMARY KEY,
    ID_CANDIDATO INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DISTRITO VARCHAR(100) NOT NULL,
    TOTAL_VOTOS INT DEFAULT 0,
    FOREIGN KEY (ID_CANDIDATO) REFERENCES CANDIDATO_DISTRITAL(ID_CANDIDATO_DISTRITAL)
);


